version: '3'
services:
  
  db-inventory:
    container_name: db-inventory
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
    volumes:
      - ./data/db-inventory:/data/db

  db-orders:
    container_name: db-orders
    image: mysql:8.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data/db-orders:/data/db

  db-products:
    container_name: db-products
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432
    volumes:
      - ./data/db-products:/data/db

  ### Zookeeper
  zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1



#  db-keycloak:
#    container_name: db-keycloak
#    image: postgres:13
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: admin  
#      POSTGRES_PASSWORD: admin
#    ports:
#      - 5433:5433
#    expose:
#      - 5433
#    command: -p 5433
#    volumes:
#      - ./data/db-keycloak:/data/db
#
#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:21.0.2
#    command: ["start-dev", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
#    ports:
#      - 8181:8181
#    expose:
#      - 8181
#    depends_on:
#      - db-keycloak
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADOR: db-keycloak
#      DB_DATABASE: db-keycloak
#      DB_PORT: 5433
#      DB_USER: admin
#      DB_PASSWORD: admin
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HTTP_PORT: 8181
#      KEYCLOAK_IMPORT: /tmp/realm-export.json
#    volumes:
#      - ./data/keycloak/realm-export.json:/tmp/realm-export.json