server:
  port: 8761

spring:
  application:
    name: discovery-service

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
